#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
# dumps the output files into a new folder obj_dir. Also generates the .mk file
verilator -Wall --cc --trace top.sv clktick.sv delay.sv f1_fsm.sv lfsr_7.sv --exe top_tb.cpp

# build C++ project via make, automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file
obj_dir/Vtop